repos:
  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        args: [ '--in-place', '--remove-all-unused-imports', '--remove-unused-variables' ]
        exclude: '^ignored_folder/|experiments/'
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        exclude: '^ignored_folder/|experiments/'
        args: [ '--profile', 'black' ]  # 使用 black 配置文件以避免 PEP8 相關問題
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        args: [--line-length=100]
        exclude: '^ignored_folder/|experiments/'

#  - repo: https://github.com/google/yapf
#    rev: v0.31.0
#    hooks:
#      - id: yapf
#        args: [ '--in-place', '--style', '.style.yapf' ]
#        exclude: ^ignored_folder/

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args:
          - --max-line-length=100
        exclude: '^ignored_folder/|experiments/'
